### ISSUE TITLE
TFT_eSPI not found

### ISSUE THREAD

**Issue by carlesoriol** [Xinyuan-LilyGO/LILYGO-T-display-RP2040#8]
TFT_eSPI not here and original is not working (and does not have factorytest as described in help) and esp32 version does not work with this board.

Where can I found it?

**Comment by LilyGO** [comment]
https://github.com/Bodmer/TFT_eSPI

**Comment by ke1g** [comment]
I don't see it there either.

I'm looking to be able to restore the pre-loaded firmware after I play with it, so if that's not what "FactoryTest" mentioned in the Arduino section of the README.md is, then I don't actually need it.  But I can't find such a file in either github repo, so I can't figure it out.
